name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: python bot.py
      timeout-minutes: 330
      continue-on-error: True

    - name: Commit and Push Changes
      if: always()
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.email "jonatangrondahl@outlook.com"
        git config --global user.name "Ephyryon"
        git add "bot_data.json"
        git add "job_data.json"
        git add "item_data.json"
        git add "user_data.json"
        git commit -m "Update JSON data files"
        git push https://$GH_PAT@github.com/Ephyryon/Koko-s-Economy.git main
      continue-on-error: True